name: Windows CI

on:
  push:
  pull_request:

jobs:
  build-win32:
    name: "Windows Build"
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install PIP Modules
      run: python -m pip install -r requirements.txt

    - name: Store Hashes
      uses: Im-Fran/git-hashes-action@v1.0.3
      
    - name: Post Hash
      run: |
        echo "def getVersion():" | Out-File -FilePath version.py -Encoding utf8
        echo "    return '$env:GIT_COMMIT_SHORT_HASH'" | Out-File -FilePath version.py -Append -Encoding utf8
        
    - name: Build Project
      run: pyinstaller --onefile .\main.py --name="Twitch Control" -w --add-data "templates/;templates/" --add-data "plugins/;plugins/"

    - name: Trusted Signing
      uses: azure/trusted-signing-action@v0.5.1
      with:
        azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        endpoint: https://eus.codesigning.azure.net/
        trusted-signing-account-name: TabithaHanegan
        certificate-profile-name: vscx-certificate-profile
        files-folder: dist/
        files-folder-filter: exe,dll
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TwitchControl-win32
        path: D:\a\TwitchControl\TwitchControl\dist
