name: Windows CI

on:
  push:
  pull_request:

jobs:
  build-win32:
    name: "Windows Build"
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install PIP Modules
      run: python -m pip install -r requirements.txt

    - name: Store Hashes
      uses: Im-Fran/git-hashes-action@v1.0.3
      
    - name: Post Hash
      run: |
        echo def getVersion(): > version.py
        echo return "%%GIT_COMMIT_SHORT_HASH%%" >> version.py
        
    - name: Build Project
      run: pyinstaller --onefile .\main.py --name="Twitch Control" -w && mkdir dist\plugins

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TwitchControl-win32
        path: D:\a\TwitchControl\TwitchControl\dist
